//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETMUONTRA
    {
        public string MaMuonTra { get; set; }
        public string MaDonViSach { get; set; }
        public string GhiChu { get; set; }
    
        public virtual SACH SACH { get; set; }
        public virtual MUONTRA MUONTRA { get; set; }
    }
}
