//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THETHUVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THETHUVIEN()
        {
            this.MUONTRAs = new HashSet<MUONTRA>();
        }
    
        public string MaThe { get; set; }
        public string MaSinhVien { get; set; }
        public Nullable<System.DateTime> NgayTaoThe { get; set; }
        public Nullable<System.DateTime> NgayGiaHan { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MUONTRA> MUONTRAs { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
